name: LumaSG
version: '${version}'
main: net.lumalyte.lumasg.LumaSGPlugin
api-version: '1.21'
load: POSTWORLD
authors:
  - BadgersMC

permissions:
  lumasg.admin:
    description: Access to admin commands
    default: op
  lumasg.play:
    description: Access to player commands
    default: true
  lumasg.*:
    description: All permissions
    default: op
    children:
      lumasg.admin: true
      lumasg.play: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Nexo:
      load: BEFORE
      required: false